# Generated by Django 3.1.5 on 2021-08-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
