# Generated by Django 3.1.5 on 2021-08-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210809_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='author',
        ),
    ]
