# Generated by Django 3.1.5 on 2021-08-09 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210809_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
