# Generated by Django 3.1.5 on 2021-08-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20210810_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='slug',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
        ),
    ]
